### ISSUE TITLE
Fix numbering

### ISSUE THREAD

**Issue by JosephineAkello** [Tambua-WomenInTech-Blog/womenintechblog#28]
![number](https://user-images.githubusercontent.com/39112051/119703820-9d96ac00-be5f-11eb-943f-37fcbbd45e00.png)

Slight oversight on numbering, should follow consistent order.

**Comment by 75pollet** [comment]
@JosephineAkello On the code the numbering is correct. I've tried pulling the latest changes and cofirmed that. You can also check the PR that was merged here https://github.com/Tambua-WomenInTech-Blog/womenintechblog/pull/23/files. I'm not sure what is causing that. any ideas?

**Comment by TheBeachMaster** [comment]
@75pollet  This is due to how the Markdown parser treats ordered  lists - example you can't have a list, then paragraph underneath it, then another space then paragraph see > [https://www.markdownguide.org/basic-syntax/#ordered-lists](https://www.markdownguide.org/basic-syntax/#ordered-lists) , [https://daringfireball.net/projects/markdown/syntax#list](https://daringfireball.net/projects/markdown/syntax#list) 

As you can see from the screenshot below - from inspect element, your ordered list keeps getting broken as you create new paragraphs

![Screenshot 2021-06-23 at 20 38 02](https://user-images.githubusercontent.com/9129843/123143378-328ec400-d463-11eb-9e90-6aa75831ee1a.png)

Here's a working ordered list

```
1. You can put a lengthy statement here
2. But that wont look nice


- Instead try - instead to create
- Unordered list

Another trick is to use headers `#`

### Header 3 as paragraph intro
- Unordered list
- Another long statement
- Note that lists don't care
```

> This renders as follows

1. You can put a lengthy statement here
2. But that wont look nice


- Instead try - instead to create
- Unordered list

Another trick is to use headers `#`

### Header 3 as paragraph intro
- Unordered list
- Another long statement
- Note that lists don't care

**Comment by 75pollet** [comment]
@TheBeachMaster thanks for the information. I'll push a PR with the fix

**Comment by JosephineAkello** [comment]
Fixed
