### ISSUE TITLE
Icon fades away when one changes to dark theme

### ISSUE THREAD

**Issue by JosephineAkello** [Tambua-WomenInTech-Blog/womenintechblog#5]
Icon fades away when one changes to dark theme, Expected behavior should allow icon color to remain visible with both dark and light theme

**Comment by TheBeachMaster** [comment]
PR #20  was approved and merged prematurely. More fixing still needed for dark theme.

<img width="1452" alt="Screenshot 2021-04-20 at 18 45 18" src="https://user-images.githubusercontent.com/9129843/115425857-a82ea780-a208-11eb-818a-2d6ff7bac58c.png">

**Comment by TheBeachMaster** [comment]
Scratch that... This was due to the way in which Brave rendered the image.

<img width="1452" alt="Screenshot 2021-04-20 at 19 27 30" src="https://user-images.githubusercontent.com/9129843/115431926-8506f680-a20e-11eb-8d6f-c00944b71f47.png">

<img width="1452" alt="Screenshot 2021-04-20 at 19 27 41" src="https://user-images.githubusercontent.com/9129843/115431915-820c0600-a20e-11eb-8098-05f5323d2478.png">

Setting Brave theme as "Dark" causes undesirable effects.
